from flask import Flask, request, jsonify
from flask_cors import CORS
import yt_dlp
import os

app = Flask(__name__)
CORS(app)

# Cookies directly code mein (string format)
YOUTUBE_COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795199769	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgEw%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	__Secure-3PSID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_V9csbeg2xHR-dJWO0Cd1CQACgYKASoSARYSFQHGX2MiM1l3XwkrNVCiJRFy4viP4xoVAUF8yKq51ZG-UPvV1bJscmjjGRFW0076
.youtube.com	TRUE	/	FALSE	1811183840	SIDCC	AKEyXzUhT9GjM4wqchbvSDQ3Q4AN-OeC84BLCgAfANDxx2OyYkxyN21I_yoqZ1HkTiWs1hgQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779734487	YSC	emX8U0_lhpA
.youtube.com	TRUE	/	FALSE	1814207752	SID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_r5br_URlFuBum9v-p_q0qwACgYKAZASARYSFQHGX2MiSMGz9HKuv9WMTSBS0-VZCRoVAUF8yKp6Z_LheqzWoG532LEMIRkP0076
.youtube.com	TRUE	/	FALSE	1779647782	ST-7zuru1	csn=Yvi_QBBvvHcPb2VF&itct=CLcBEIf2BBgAIhMI4dm1ycjSlAMV9oPKAh01eRy4Wg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBOHjDts%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183752	__Secure-1PSIDTS	sidts-CjQBhkeRd_LWhIieF8OqBmbqFhyj0ZhZCywmjsRBOuLTLl8h0mabDQxBJM5YLqQIfqNjbPW3EAA
.youtube.com	TRUE	/	TRUE	1779648375	CONSISTENCY	AHzIXrzfoqSdbfKfacROWLsqWW54qkiVmKUOaT5sKeSqCsfn7UqMhlZodlnjRb73CSFXbdO0riYSXeo8Q9UZM5iI0HPBx-07ZZuxmyvmezK9ZhNrJ7ULdh4zPi8
.youtube.com	TRUE	/	TRUE	1814207752	SAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183840	__Secure-1PSIDCC	AKEyXzV3Q8yc8GI9Q0EIcT8UaGerpjfUgS_Af1W1tz5MyJP-zhwXxltnrkFbKugBrlYIpY61
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	SSID	AuFkoBC5Q5eSwWpRX
.youtube.com	TRUE	/	TRUE	1814207752	__Secure-1PAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	__Secure-1PSID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_4pZYFPsFJs4M6L9JcSdfHQACgYKAawSARYSFQHGX2MiCGkXHFuwI5yTcpb-wkptkBoVAUF8yKoxjYwbom3m9F9XwfFgludD0076
.youtube.com	TRUE	/	TRUE	1814207752	__Secure-3PAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183840	__Secure-3PSIDCC	AKEyXzXOxdapFuw7-M2HciouvDVfLlUGofpIwG5_o6zLYki_W6TX2T60v4E1fruPtQxdAdtd
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183752	__Secure-3PSIDTS	sidts-CjQBhkeRd_LWhIieF8OqBmbqFhyj0ZhZCywmjsRBOuLTLl8h0mabDQxBJM5YLqQIfqNjbPW3EAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795199769	__Secure-YNID	18.YT=gIJo0S4oItGZDyupA_-XXhn6M-QmR7Y1oPWdcOX2mwSjmsq8FXVgk-8qyb2nskLiQFDsrr9dlejeEv9Ul8EZAjBoQ0U2ji0MgOYzHAWbLg7lNi4DKbkB-gxC0WnkyArPNPS3NqSDQ_L67JeE2vpBUibWgGVLlXOSfL0aeA8eOZC47X1ph5BChxgngH1SiLKFjpqnWJSPuw-Z72GxzeRNMGYFIF6_ET7PuZZAC-otlKe8kcZVOJHtwmXRj1F0qrPQpWevoy_1SHhf9TAqt3SMnEKZh3dsYgXJgT_wdmOZjbUL0UcDZWF1SJQ58zVYXAXaLrx1lrd0ikjqlFvcw3lrKg
.youtube.com	TRUE	/	FALSE	1814207752	APISID	9L1uamWZPGeNQCby/AwkF_BL5sU8ogl8nL
#HttpOnly_.youtube.com	TRUE	/	FALSE	1814207752	HSID	Ar7sttDsnrQxVPNtJ
.youtube.com	TRUE	/	TRUE	1814207769	PREF	f6=40000000&tz=Asia.Kolkata
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795199769	VISITOR_INFO1_LIVE	T8c1SB_VCi4
"""

COOKIE_FILE = "/tmp/yt_cookies.txt"

def setup_cookies():
    if not os.path.exists(COOKIE_FILE):
        with open(COOKIE_FILE, 'w') as f:
            f.write(YOUTUBE_COOKIES)

setup_cookies()

@app.route('/')
def home():
    return jsonify({"status": "EmYtSave API Running"})

@app.route('/info', methods=['GET'])
def get_info():
    url = request.args.get('url')
    if not url:
        return jsonify({"error": "URL required"}), 400
    try:
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'cookiefile': COOKIE_FILE,
            'extractor_args': {
                'youtube': {
                    'player_client': ['android', 'web'],
                }
            },
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36',
            }
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            formats = []
            for f in info.get('formats', []):
                if f.get('vcodec') != 'none' and f.get('height'):
                    formats.append({
                        "format_id": f['format_id'],
                        "quality": f"{f['height']}p",
                        "ext": f.get('ext', 'mp4'),
                        "url": f['url']
                    })
                elif f.get('acodec') != 'none' and f.get('vcodec') == 'none':
                    formats.append({
                        "format_id": f['format_id'],
                        "quality": "audio",
                        "ext": f.get('ext', 'mp3'),
                        "url": f['url']
                    })
            return jsonify({
                "title": info.get('title'),
                "thumbnail": info.get('thumbnail'),
                "formats": formats
            })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
