from flask import Flask, request, jsonify, send_from_directory, Response
from flask_cors import CORS
import yt_dlp
import os
import re
import urllib.request

app = Flask(__name__)
CORS(app)

# Cookies — Render Secret File se load hogi (/etc/secrets/cookies.txt)
# Fallback: hardcoded (backup ke liye)
COOKIE_FILE = "/etc/secrets/cookies.txt"

FALLBACK_COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795242073	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgEw%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	__Secure-3PSID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_V9csbeg2xHR-dJWO0Cd1CQACgYKASoSARYSFQHGX2MiM1l3XwkrNVCiJRFy4viP4xoVAUF8yKq51ZG-UPvV1bJscmjjGRFW0076
.youtube.com	TRUE	/	FALSE	1811226073	SIDCC	AKEyXzW2jYRWn9EOFgo8YDqtEa_4BUVwsQGn2J8ZzQ12Yc2TG0IlpOfYarAmuzO1PcyDi4tV
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779776480	YSC	cJIOpDIHP6o
.youtube.com	TRUE	/	FALSE	1814207752	SID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_r5br_URlFuBum9v-p_q0qwACgYKAZASARYSFQHGX2MiSMGz9HKuv9WMTSBS0-VZCRoVAUF8yKp6Z_LheqzWoG532LEMIRkP0076
.youtube.com	TRUE	/	FALSE	1779647782	ST-7zuru1	csn=Yvi_QBBvvHcPb2VF&itct=CLcBEIf2BBgAIhMI4dm1ycjSlAMV9oPKAh01eRy4Wg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBOHjDts%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183752	__Secure-1PSIDTS	sidts-CjQBhkeRd_LWhIieF8OqBmbqFhyj0ZhZCywmjsRBOuLTLl8h0mabDQxBJM5YLqQIfqNjbPW3EAA
.youtube.com	TRUE	/	TRUE	1779659566	CONSISTENCY	AHzIXrze1XZBWc3wXa9PksN8kHJrTiT09Y0xq-5S6LUZm7qRIDKutArXXXszhlHvUTxD0hTPritDxH7gWRJ5JAd17EHeTgaPoabBR7mrRnlv6IMwi8TV0Whq7xw
.youtube.com	TRUE	/	TRUE	1814207752	SAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811226073	__Secure-1PSIDCC	AKEyXzUstFpeM2wQc4kgAtvxirOcnonBFXz45Sawdy29PQUIfIRpd_iRMmE4VizBN5d1UwLI
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	SSID	AuFkoBC5Q5eSwWpRX
.youtube.com	TRUE	/	TRUE	1814207752	__Secure-1PAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	__Secure-1PSID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_4pZYFPsFJs4M6L9JcSdfHQACgYKAawSARYSFQHGX2MiCGkXHFuwI5yTcpb-wkptkBoVAUF8yKoxjYwbom3m9F9XwfFgludD0076
.youtube.com	TRUE	/	TRUE	1814207752	__Secure-3PAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811226073	__Secure-3PSIDCC	AKEyXzWjxAip3AmUVyej-WhMlSte3orV1Dc2Rm2ppKRBFYxsYzn0V0Lv25jcCcFwpUtv3tE1
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183752	__Secure-3PSIDTS	sidts-CjQBhkeRd_LWhIieF8OqBmbqFhyj0ZhZCywmjsRBOuLTLl8h0mabDQxBJM5YLqQIfqNjbPW3EAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795199769	__Secure-YNID	18.YT=txi-fjVxL7N_zQS6wOK7Ghuegs36TJPthuauJARBmDb3HVO9QL55wVjiGUc4Wn5JaYDblGrTepQJTJI_QhsW61KwDeLtcuvlpFGIsOUnF0k7ua4FOGgyziHeIyC6mVEd5agn16PTa9b9p1c6AjcIdMZiGbPILRn1D10_EsmYQkASJ_5QHEs6RDFIsAnKeAIaUv2HtGKBPW9c0AHUU1F_psh7hZVlriUw6JZ-DJNrSkSaiXtn9MLJ3jlcy7gdlr49F71GnFuvvaS8SHPz4u6-7ZFswu3fGz58PF3fLQgcWM2814r5chRPIs13ITtS4FhoKqbMxNgX-5avRCP7FNBISQ
.youtube.com	TRUE	/	FALSE	1814207752	APISID	9L1uamWZPGeNQCby/AwkF_BL5sU8ogl8nL
#HttpOnly_.youtube.com	TRUE	/	FALSE	1814207752	HSID	Ar7sttDsnrQxVPNtJ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814215362	LOGIN_INFO	AFmmF2swRAIgPoS9IfF7tnq97jA50a3GYltZWJ4w_7d-2CTkgbfC2EgCIH3KStkSrR-if8W6F7krBSa3cU0ovy_5MwOXAaaydTZY:QUQ3MjNmeExjNmNFSVJkTEZMZ3gxSEhDWk5kMURsU3RoVzNjZjBSc1BtcVN5ek53ZkdmaHgtZXVJQTdFTEV6TlNJcXRfal9NMkNTRG1WcDVVVV9ySWlaWUFvRUVmeVVMN0JHbGFoSGdYTTRqRkNnUGliTTFBbWFYMEhJNy1JQmltLWFVR1NPYldQYXViN3c3OHlMalJSZU15VWVBcE50eFln
.youtube.com	TRUE	/	TRUE	1814250073	PREF	f6=40000000&tz=Asia.Kolkata
.youtube.com	TRUE	/	FALSE	1779655770	ST-143rz7l	csn=1KZSLkeHbbQJrbr_&itct=CB4Q08wBGAEiEwiuq6Lu5NKUAxWfV50JHeeZHJcyBmctaGlnaMoBBOHjDts%3D
.youtube.com	TRUE	/	FALSE	1779655770	ST-143rzdt	csn=1KZSLkeHbbQJrbr_&itct=CB0Q08wBGAIiEwiuq6Lu5NKUAxWfV50JHeeZHJcyBmctaGlnaMoBBOHjDts%3D
.youtube.com	TRUE	/	FALSE	1779658973	ST-17e5lws	csn=nnj4cCSuEJAFG2m9&itct=CLcBEIf2BBgAIhMIxdPTn_LSlAMVqN5VCR0kmDsHWg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBOHjDts%3D
.youtube.com	TRUE	/	FALSE	1779689800	ST-1fzc799	csn=Mq6T3jCWgJ_1KDwW&itct=CKQBEIf2BBgBIhMIu-qfjeXTlAMVF4FWAR1pjxHcWg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBOHjDts%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795242073	VISITOR_INFO1_LIVE	T8c1SB_VCi4
"""

FALLBACK_COOKIE_FILE = "/tmp/yt_cookies_fallback.txt"

ACTIVE_COOKIE_FILE = "/tmp/yt_cookies_active.txt"

def get_cookie_file():
    """Always use /tmp — copy from Secret File or use fallback"""
    try:
        if os.path.exists(COOKIE_FILE):
            # Copy read-only secret file to writable /tmp
            with open(COOKIE_FILE, 'r') as src:
                data = src.read()
            with open(ACTIVE_COOKIE_FILE, 'w') as dst:
                dst.write(data)
            return ACTIVE_COOKIE_FILE
    except Exception:
        pass
    # Use fallback cookies
    with open(ACTIVE_COOKIE_FILE, 'w') as f:
        f.write(FALLBACK_COOKIES)
    return ACTIVE_COOKIE_FILE

# Setup cookies on startup
get_cookie_file()

YDL_BASE_OPTS = {
    'quiet': True,
    'no_warnings': True,
    'cookiefile': get_cookie_file(),
    'http_headers': {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    }
}

def safe_filename(title):
    return re.sub(r'[^\w\s-]', '', title or 'video').strip()[:60]


@app.route('/')
def index():
    return send_from_directory('.', 'index.html')


@app.route('/api')
def home():
    return jsonify({"status": "EmYtSave API Running"})


@app.route('/info', methods=['GET'])
def get_info():
    url = request.args.get('url')
    if not url:
        return jsonify({"error": "URL required"}), 400
    try:
        ydl_opts = {**YDL_BASE_OPTS, 'cookiefile': get_cookie_file(), 'skip_download': True}

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            formats = []
            seen_heights = set()

            for f in info.get('formats', []):
                height = f.get('height')
                vcodec = f.get('vcodec', 'none')
                acodec = f.get('acodec', 'none')
                fmt_url = f.get('url', '')
                protocol = f.get('protocol', '')

                if not fmt_url:
                    continue

                # Only combined streams (video+audio both present) — no FFmpeg needed
                if vcodec != 'none' and acodec != 'none' and height and height not in seen_heights:
                    seen_heights.add(height)
                    formats.append({
                        "format_id": f.get('format_id'),
                        "quality": f"{height}p",
                        "ext": f.get('ext', 'mp4'),
                        "filesize": f.get('filesize') or f.get('filesize_approx')
                    })
                # Best audio only
                elif vcodec == 'none' and acodec != 'none' and not any(x['quality'] == 'audio' for x in formats):
                    formats.append({
                        "format_id": f.get('format_id'),
                        "quality": "audio",
                        "ext": f.get('ext', 'm4a'),
                        "filesize": f.get('filesize') or f.get('filesize_approx')
                    })

            video_fmts = sorted(
                [f for f in formats if f['quality'] != 'audio'],
                key=lambda x: int(x['quality'].replace('p', '')),
                reverse=True
            )
            audio_fmts = [f for f in formats if f['quality'] == 'audio']

            return jsonify({
                "title": info.get('title'),
                "thumbnail": info.get('thumbnail'),
                "duration": info.get('duration'),
                "formats": video_fmts + audio_fmts
            })

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/download', methods=['GET'])
def download():
    yt_url  = request.args.get('url')
    quality = request.args.get('quality', 'best')
    title   = request.args.get('title', 'video')
    is_audio = quality == 'audio'

    if not yt_url:
        return jsonify({"error": "URL required"}), 400

    try:
        if is_audio:
            fmt = 'bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio'
            ext = 'm4a'
        else:
            h = quality.replace('p', '')
            # Only progressive (video+audio combined) streams — no FFmpeg needed
            fmt = (
                f'worstvideo[height>={h}][vcodec!=none][acodec!=none][ext=mp4]'
                f'/best[height<={h}][vcodec!=none][acodec!=none][ext=mp4]'
                f'/best[height<={h}][vcodec!=none][acodec!=none]'
                f'/best[vcodec!=none][acodec!=none][ext=mp4]'
                f'/best[vcodec!=none][acodec!=none]'
            )
            ext = 'mp4'

        ydl_opts = {
            **YDL_BASE_OPTS,
            'cookiefile': get_cookie_file(),
            'skip_download': True,
            'format': fmt,
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(yt_url, download=False)
            if info.get('url'):
                stream_url = info['url']
            elif info.get('requested_formats'):
                stream_url = info['requested_formats'][0]['url']
            elif info.get('formats'):
                stream_url = info['formats'][-1]['url']
            else:
                return jsonify({"error": "Could not get stream URL"}), 500
            real_title = info.get('title', title)

        filename = f"{safe_filename(real_title)}.{ext}"

        # Redirect to stream URL directly — avoids Render timeout on free plan
        from flask import redirect
        response = redirect(stream_url, code=302)
        response.headers['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response

    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
