from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import yt_dlp
import os

app = Flask(__name__)
CORS(app)

YOUTUBE_COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795207776	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgEw%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	__Secure-3PSID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_V9csbeg2xHR-dJWO0Cd1CQACgYKASoSARYSFQHGX2MiM1l3XwkrNVCiJRFy4viP4xoVAUF8yKq51ZG-UPvV1bJscmjjGRFW0076
.youtube.com	TRUE	/	FALSE	1811191779	SIDCC	AKEyXzVRgakDq5Z-wXtz_u5w9iWPjMuyhHfa8VVD-G3AF1fscDwqCMKqD6ak__v0o62z_O5c
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779742182	YSC	emX8U0_lhpA
.youtube.com	TRUE	/	FALSE	1814207752	SID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_r5br_URlFuBum9v-p_q0qwACgYKAZASARYSFQHGX2MiSMGz9HKuv9WMTSBS0-VZCRoVAUF8yKp6Z_LheqzWoG532LEMIRkP0076
.youtube.com	TRUE	/	FALSE	1779647782	ST-7zuru1	csn=Yvi_QBBvvHcPb2VF&itct=CLcBEIf2BBgAIhMI4dm1ycjSlAMV9oPKAh01eRy4Wg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBOHjDts%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183752	__Secure-1PSIDTS	sidts-CjQBhkeRd_LWhIieF8OqBmbqFhyj0ZhZCywmjsRBOuLTLl8h0mabDQxBJM5YLqQIfqNjbPW3EAA
.youtube.com	TRUE	/	TRUE	1779648375	CONSISTENCY	AHzIXrzfoqSdbfKfacROWLsqWW54qkiVmKUOaT5sKeSqCsfn7UqMhlZodlnjRb73CSFXbdO0riYSXeo8Q9UZM5iI0HPBx-07ZZuxmyvmezK9ZhNrJ7ULdh4zPi8
.youtube.com	TRUE	/	TRUE	1814207752	SAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811191779	__Secure-1PSIDCC	AKEyXzWJ5bJ2W2iUlP8zcjuhSVI0GIfzI5_cfyeP0NMrvFdCeQxHcADdUiJVdSvwtfBkQCgu
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	SSID	AuFkoBC5Q5eSwWpRX
.youtube.com	TRUE	/	TRUE	1814207752	__Secure-1PAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814207752	__Secure-1PSID	g.a000-QjmGM-xD2jaWRudBmZ1lUwLHWzgvyET_pcGPosGVZkP9gJ_4pZYFPsFJs4M6L9JcSdfHQACgYKAawSARYSFQHGX2MiCGkXHFuwI5yTcpb-wkptkBoVAUF8yKoxjYwbom3m9F9XwfFgludD0076
.youtube.com	TRUE	/	TRUE	1814207752	__Secure-3PAPISID	IqhCmiILmXbqWmVH/ALtKn8WuYeAQ6roA2
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811191779	__Secure-3PSIDCC	AKEyXzXlCQo4xzqSkxxhdU5MNXgHEYSy8GEVvcblyer7Sqm8J0f_5hKBayseMtfe-A4uduGB
#HttpOnly_.youtube.com	TRUE	/	TRUE	1811183752	__Secure-3PSIDTS	sidts-CjQBhkeRd_LWhIieF8OqBmbqFhyj0ZhZCywmjsRBOuLTLl8h0mabDQxBJM5YLqQIfqNjbPW3EAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795199769	__Secure-YNID	18.YT=txi-fjVxL7N_zQS6wOK7Ghuegs36TJPthuauJARBmDb3HVO9QL55wVjiGUc4Wn5JaYDblGrTepQJTJI_QhsW61KwDeLtcuvlpFGIsOUnF0k7ua4FOGgyziHeIyC6mVEd5agn16PTa9b9p1c6AjcIdMZiGbPILRn1D10_EsmYQkASJ_5QHEs6RDFIsAnKeAIaUv2HtGKBPW9c0AHUU1F_psh7hZVlriUw6JZ-DJNrSkSaiXtn9MLJ3jlcy7gdlr49F71GnFuvvaS8SHPz4u6-7ZFswu3fGz58PF3fLQgcWM2814r5chRPIs13ITtS4FhoKqbMxNgX-5avRCP7FNBISQ
.youtube.com	TRUE	/	FALSE	1814207752	APISID	9L1uamWZPGeNQCby/AwkF_BL5sU8ogl8nL
#HttpOnly_.youtube.com	TRUE	/	FALSE	1814207752	HSID	Ar7sttDsnrQxVPNtJ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814215362	LOGIN_INFO	AFmmF2swRAIgPoS9IfF7tnq97jA50a3GYltZWJ4w_7d-2CTkgbfC2EgCIH3KStkSrR-if8W6F7krBSa3cU0ovy_5MwOXAaaydTZY:QUQ3MjNmeExjNmNFSVJkTEZMZ3gxSEhDWk5kMURsU3RoVzNjZjBSc1BtcVN5ek53ZkdmaHgtZXVJQTdFTEV6TlNJcXRfal9NMkNTRG1WcDVVVV9ySWlaWUFvRUVmeVVMN0JHbGFoSGdYTTRqRkNnUGliTTFBbWFYMEhJNy1JQmltLWFVR1NPYldQYXViN3c3OHlMalJSZU15VWVBcE50eFln
.youtube.com	TRUE	/	TRUE	1814215776	PREF	f6=40000000&tz=Asia.Kolkata
.youtube.com	TRUE	/	FALSE	1779655770	ST-143rz7l	csn=1KZSLkeHbbQJrbr_&itct=CB4Q08wBGAEiEwiuq6Lu5NKUAxWfV50JHeeZHJcyBmctaGlnaMoBBOHjDts%3D
.youtube.com	TRUE	/	FALSE	1779655770	ST-143rzdt	csn=1KZSLkeHbbQJrbr_&itct=CB0Q08wBGAIiEwiuq6Lu5NKUAxWfV50JHeeZHJcyBmctaGlnaMoBBOHjDts%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1795207776	VISITOR_INFO1_LIVE	T8c1SB_VCi4
"""

COOKIE_FILE = "/tmp/yt_cookies.txt"

def setup_cookies():
    with open(COOKIE_FILE, 'w') as f:
        f.write(YOUTUBE_COOKIES)

setup_cookies()

@app.route('/')
def index():
    return send_from_directory('.', 'index.html')

@app.route('/api')
def home():
    return jsonify({"status": "EmYtSave API Running"})

@app.route('/info', methods=['GET'])
def get_info():
    url = request.args.get('url')
    if not url:
        return jsonify({"error": "URL required"}), 400
    try:
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'cookiefile': COOKIE_FILE,
            'skip_download': True,
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36',
            }
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

            formats = []
            seen_heights = set()

            for f in info.get('formats', []):
                height = f.get('height')
                vcodec = f.get('vcodec', 'none')
                acodec = f.get('acodec', 'none')
                fmt_url = f.get('url', '')
                protocol = f.get('protocol', '')

                # Skip manifests
                if not fmt_url or protocol in ('m3u8', 'm3u8_native', 'dash'):
                    continue

                # Video formats
                if vcodec != 'none' and height and height not in seen_heights:
                    seen_heights.add(height)
                    formats.append({
                        "format_id": f.get('format_id'),
                        "quality": f"{height}p",
                        "ext": f.get('ext', 'mp4'),
                        "url": fmt_url,
                        "filesize": f.get('filesize') or f.get('filesize_approx')
                    })

                # Audio only
                elif vcodec == 'none' and acodec != 'none':
                    formats.append({
                        "format_id": f.get('format_id'),
                        "quality": "audio",
                        "ext": f.get('ext', 'm4a'),
                        "url": fmt_url,
                        "filesize": f.get('filesize') or f.get('filesize_approx')
                    })

            # Sort video high to low
            video_fmts = sorted(
                [f for f in formats if f['quality'] != 'audio'],
                key=lambda x: int(x['quality'].replace('p', '')),
                reverse=True
            )
            audio_fmts = [f for f in formats if f['quality'] == 'audio']

            return jsonify({
                "title": info.get('title'),
                "thumbnail": info.get('thumbnail'),
                "duration": info.get('duration'),
                "formats": video_fmts + audio_fmts
            })

    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
